version: "3.7"
services:
  ###########
  ## MySQL ##
  ###########
  mysql:
    image: mysql/mysql-server:5.7.27
    restart: "no"
    command: --character_set_server=utf8mb4 --max_allowed_packet=1073741824
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=social
      - MYSQL_USER=lbry
      - MYSQL_PASSWORD=lbry
      - MYSQL_LOG_CONSOLE=true
 #############
  ## Adminer ##
  #############
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
